export const COFFEES_LOADING = 'COFFEES_LOADING';
export const ADD_COFFEES = 'ADD_COFFEES';
export const COFFEES_FAILED = 'COFFEES_FAILED';

export const SUITES_LOADING = 'SUITES_LOADING';
export const ADD_SUITES = 'ADD_SUITES';
export const SUITES_FAILED = 'SUITES_FAILED';

export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';

export const CLOTHES_LOADING = 'CLOTHES_LOADING';
export const ADD_CLOTHES = 'ADD_CLOTHES';
export const CLOTHES_FAILED = 'CLOTHES_FAILED';

export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';